### ISSUE TITLE
want mechanism for testing `mdata-get`

### ISSUE THREAD

**Issue by bixu** [bixu/lx_kitchen#4]
Is this even possible on standalone SmartOS?

**Comment by sjorge** [comment]
Yep :)

Although it was only working on Ubuntu dataset for me.

**Comment by bixu** [comment]
Have an example handy?

**Comment by sjorge** [comment]
Issue #3 has a nice example actually

**Comment by bixu** [comment]
Fixed with https://github.com/bixu/lx_kitchen/commit/da022de4a4b21f399c843c165eee154cac7affe4
